// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Este archivo solo lo lee la Prisma CLI (migrate, studio, db pull...), nunca
// la app en runtime — por eso usa la conexión DIRECTA (puerto 5432 en Supabase):
// Prisma 7 ya no soporta `directUrl` para separar migraciones del pooler (fue
// quitado del tipo `Datasource` de @prisma/config), y correr `migrate` a
// través de pgbouncer en modo transacción falla. El cliente Prisma en runtime
// (src/lib/prisma.ts) usa su propio driver adapter apuntando a DATABASE_URL
// (pooled, puerto 6543), independiente de este archivo.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
